version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    open-pull-requests-limit: 10
    groups:
      npm_and_yarn:
        patterns:
          - "*"
    commit-message:
      prefix: "chore(deps):"
      prefix-development: "chore(deps-dev):"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    commit-message:
      prefix: "chore(deps):"
